version: '3'

tasks:
  # Used to spin up some VMs to practice kubeadm commands and clean them up. 
  kubeadm: 
    cmds: 
      - ./deploy-virtual-machines.sh

    silent: true

  kubeadm_clean:
    cmds:
      - ./delete-virtual-machines.sh
  
  kind: # Quickly spin up a cluster to work on concepts
