version: '3'

tasks:
  # Used to spin up some VMs to practice kubeadm commands and clean them up. 
  kubeadm: 
    cmds: 
      - ./deploy-virtual-machines.sh
    silent: true

  kubeadm_setup: # automate configuration up to the point where kubeadm init can be run
    vars:
      VM_LIST: 
        sh: multipass list | awk '{print $1}' | tail -n +2 | sed -n '/^[[:space:]]*[a-zA-Z]/p'
      SCRIPT:
        sh: ./scripts/kubeadm-setup.sh
    cmds:
      - for: { var: VM_LIST, var: SCRIPT }
        cmd: multipass exec {{ .ITEM }} {{ .SCRIPT }}


  kubeadm_clean:
    cmds:
      - ./delete-virtual-machines.sh
  
  kind: # Quickly spin up a cluster to work on concepts
