version: '3'

tasks:
  # Used to spin up some VMs to practice kubeadm commands and clean them up. 
  kubeadm: 
    cmds: 
      - ./deploy-virtual-machines.sh
      - multipass list
    silent: true

  kubeadm_setup: # automate configuration up to the point where kubeadm init can be run
    vars:
      VM_LIST: 
        sh: multipass list | awk '{print $1}' | tail -n +2 | sed -n '/^[[:space:]]*[a-zA-Z]/p'
    cmds:
      - for: { var: VM_LIST }
        cmd: multipass transfer ./scripts/kubeadm-setup.sh {{ .ITEM }}:. && multipass exec {{ .ITEM }} ./kubeadm-setup.sh

  kubeadm_clean:
    cmds:
      - ./delete-virtual-machines.sh
  
  kind: # Quickly spin up a cluster to work on concepts
